### ISSUE TITLE
Adicionar Configuração para swagger

### ISSUE THREAD

**Issue by vitorAzevedo09** [dedevpradev/faladev#18]
## Descrição

Esta issue propõe a adição da documentação Swagger à API do projeto para melhorar a clareza, facilidade de uso e integração com outros sistemas.

## Objetivo

Implementar a documentação Swagger para descrever de forma detalhada os endpoints, parâmetros, tipos de resposta e exemplos de uso da API. 

## Justificativa

A documentação Swagger oferece uma interface interativa que facilita a compreensão e teste dos endpoints da API. Ela padroniza a documentação, promovendo a consistência e facilitando a integração com ferramentas de terceiros. Além disso, simplifica o processo de onboarding para novos desenvolvedores e ajuda na manutenção contínua do sistema, garantindo que a API seja sempre bem documentada e atualizada.

obs: Sugestão de utilização do módulo gin-swagger

**Comment by mffonseca** [comment]
@vitorAzevedo09 acabei de testar o PR e encontrei alguns pequenos detalhes.

- Rotas não condizem exatamente com as definidas em http.StartServer
- Cabeçalho da doc ausente

![Captura de Tela 2024-07-24 às 08 22 19](https://github.com/user-attachments/assets/e3ba825a-fd60-4b42-b340-cfabf939c4f4)

Consegue subir um novo PR com esses ajustes? 

No mais, ficou muito bom. Parabéns.

**Comment by vitorAzevedo09** [comment]
Opa, consigo sim.
