### ISSUE TITLE
Criar interface para cadastro de usuários

### ISSUE THREAD

**Issue by mffonseca** [dedevpradev/faladev#35]

**Comment by alekgomes** [comment]
@mffonseca, tenho interesse nessa tarefa. Posso fazê-la?

O objetivo é termos uma tela com um formulário para cadastrar novos mentores, certo?

Acho que podemos replicar o mesmo estilo de inputs e botão da landing page pra termos um cadastro inical com informações básicas enquanto não definimos a tabela de mentores no backend.

**Comment by mffonseca** [comment]
@alekgomes fica a vontade, mas mudei a tarefa para cadastro de usuários, uma vez que um usuário pode ser tanto mentor quanto mentorado, a diferença é que consideraremos mentor todos os usuários que tenha pelo menos uma mentoria cadastrada. Concorda?

Podemos considerar por enquanto os campos id, name, email, phone, password

**Comment by alekgomes** [comment]
@mffonseca, abri [esse PR aqui](https://github.com/dedevpradev/faladev/pull/40) referente à essa tarefa.
