### ISSUE TITLE
Ter/criar um repo separado para o frontend

### ISSUE THREAD

**Issue by felipe-andersen** [dedevpradev/faladev#55]
Separar o frontend do restante criando um repositório próprio. Criar um arquivo Dockerfile (containerizar).

**Comment by mffonseca** [comment]
@felipe-andersen já tivemos essa discussão em um fórum em grupo e optamos em manter em um monorepo para facilitar a integração de novos membros no que tange a configuração, e setup do projeto.

Do jeito que está, após clonar o repositório, considerando que você tem o docker instalado em sua máquina, você conseguiria subir todo ambiente, incluindo front, back-end e demais serviços apenas com: **docker compose up**

Caso não esteja conseguindo, podemos combinar um momento para vermos isso.
